import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashboardSidebar from "../components/dashboard-sidebar";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	colorScheme: "dark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className + " flex h-screen"}>
				<ClerkProvider>
					<DashboardSidebar />
				</ClerkProvider>
				{children}
			</body>
		</html>
	);
}
