[package]
name = "realtime"
version = "0.1.0"
edition = "2021"

[dependencies]
axum-extra = { version = "*" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "*", features = ["ws", "macros"] }
futures-util = "*"
serde_json = "*"
