name: Code quality

on:
  push: # run for every merge/push to main and dev branch
    branches: [main, dev]
  pull_request: # run for every PR against main branch
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.6.0

      - name: Run Biome
        run: biome ci .