name: Deploy Workers - Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/workers/**"

jobs:
  deploy:
    name: Deploy Workers API
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Deploy To Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          preCommands: pnpm install
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/workers
          environment: production